### ISSUE TITLE
Docstrings are not preserved correctly.

### ISSUE THREAD

**Issue by leovp** [JelleZijlstra/ast_decompiler#1]
Currently it's impossible to correctly preserve docstrings. This test shows the issue:
```
from .tests import assert_decompiles


def test_docstrings():
    assert_decompiles('''
def a():
    """
    Docstring.
    """
    return 1
''', '''def a():
 """
 Docstring.
 """
 return 1
''', indentation=1)
```

Result:
```
>>> expected
def a():
 """
 Docstring.
 """
 return 1

>>> actual
def a():
 '\n    Docstring.\n    '
 return 1
```

Thoughts: when processing the function body in `write_function_def` we should look at the very first node in the function's body. If the node is of type Expr, and contains a string, then it's most likely docstring of this function and should be processed accordingly.

**Comment by JelleZijlstra** [comment]
Yes, this would be a good enhancement. Currently all strings are simply decompiled using `repr()`, but if the string is a module, class, or function (including async function) docstring, we should instead enclose it in `"""` and emit newlines as actual newlines instead of `\n`.

Feel free to submit a pull request to make this change if you're interested. Otherwise, I'll try to get to this soon.
