### ISSUE TITLE
Goal of the project

### ISSUE THREAD

**Issue by patrick91** [JelleZijlstra/ast_decompiler#50]
Hi @JelleZijlstra! This project looks amazing, can you share some of the goals and needs of it?

I was thinking I could use it for a generating code, so my script would generate ast from something and then use ast_decompiler to generate python code, would it make sense? Or should I stick with using jinja for generating code? 😊

**Comment by JelleZijlstra** [comment]
My original motivation was in https://github.com/quora/pyanalyze for suggesting autofixes for problems it detects. An AST decompiler is a good fit there because pyanalyze works on an AST, and autofixes often involve moving around pieces of AST. The disadvantage is that it removes comments, and occasionally autofixes touch lines with comments.

As of Python 3.9 there is a builtin `ast.unparse` function (https://docs.python.org/3.10/library/ast.html#ast.unparse) that does the same thing as `ast_decompiler`. This package has a few more options than `ast.unparse`, but I don't think the differences really matter, so I expect this package to become obsolete over time. I'm not currently planning on adding new features, but I'd be happy to help out with any necessary fixes if `ast_decompiler` is a good fit for your use case.

**Comment by patrick91** [comment]
I see! Thanks for sharing, and I definitely didn't know about `ast.unparse`, sounds great!

I'll close the issue ^^
